### ISSUE TITLE
[Vue warn]: Unknown custom element: <search> -

### ISSUE THREAD

**Issue by plweil** [vuejs/v2.vuejs.org#2990]
`<search>`is a legitimate [html5 element](https://html.spec.whatwg.org/multipage/grouping-content.html#the-search-element). Why is Vue (v2.6.12) complaining that it is unknown?

`[Vue warn]: Unknown custom element: <search> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
`

In the template section of my component:

```javascript
           <template>
          <div>
             <search>
              <label for="uw-major-search" class="text-search">Keyword Search</label>
                <input
                    id="uw-major-search"
                    class="uw-program-search"
                    name="uw-major-search"
                    v-model="majorSearchInput"
                    type="search"
                >
                
                [search results and other stuff]
                </search>
           </div>
          </template>
```

**Comment by Jinjiang** [comment]
Hi @plweil glad you found this. Let me explain:

- This `<search>` element was officially added into WHATWG HTML spec as a living standard on March 24th 2023, which was 3 weeks ago https://github.com/whatwg/html/pull/7320#event-8833972345
- Vue (v2.6.12) was officially published on Aug 20th 2020, which was 3 years ago [npm link](https://www.npmjs.com/package/vue?activeTab=versions)

So I'm sorry we couldn't meet your expectation. I hope you'll be able to understand that.

And since it's not a docs-related issue. I'm going to close it if you don't mind. Thanks.

**Comment by plweil** [comment]
Yes, I didn't realize that it was added so recently. My apologies. Thank you.
